feat: add command installation prompts for missing tools

diff --git a/bin/new b/bin/new
--- a/bin/new
+++ b/bin/new
@@ -6,12 +6,14 @@ if [[ $TERM == *color* ]]; then
   COLOR_TYPE="\e[1;33m"
   COLOR_APP_NAME="\e[1;34m"
   COLOR_ARGUMENTS="\e[1;35m" 
+  COLOR_ERROR="\e[1;31m"
   COLOR_RESET="\e[0m"
 else
   COLOR_NEW=""
   COLOR_TYPE=""
   COLOR_APP_NAME=""
   COLOR_ARGUMENTS="" 
+  COLOR_ERROR=""
   COLOR_RESET=""
 fi
 
@@ -88,13 +90,52 @@ TYPE=$1
 APP_NAME=$2
 ARGUMENTS="${@:3}"  # Capture all arguments from the third one onward
 
+# Function to check if a command exists
+check_command() {
+  command -v "$1" >/dev/null 2>&1 || {
+    printf "${COLOR_ERROR}Error: The command '%s' is not found. Would you like to install it?${COLOR_RESET} (y/n)\n" "$1"
+    read -r answer
+    if [[ "$answer" == "y" ]]; then
+      case "$1" in
+        ng)
+          printf "Installing Angular CLI...\n"
+          npm install -g @angular/cli
+          ;;
+        cargo)
+          printf "Installing Rust and Cargo...\n"
+          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
+          printf "Please add \$HOME/.cargo/bin to your PATH.\n"
+          ;;
+        composer)
+          printf "Installing Composer...\n"
+          curl -sS https://getcomposer.org/installer | php
+          mv composer.phar /usr/local/bin/composer
+          ;;
+        # Add other commands as needed
+        *)
+          printf "${COLOR_ERROR}No installation script available for '%s'. Please install it manually.${COLOR_RESET}\n" "$1"
+          ;;
+      esac
+    else
+      printf "${COLOR_ERROR}Aborting project creation.${COLOR_RESET}\n"
+      exit 1
+    fi
+  }
+}
+
+
 # Check if the project type is supported
 for i in "${!PROJECT_TYPES[@]}"; do
     if [[ "$TYPE" == "${PROJECT_TYPES[$i]}" ]]; then
         command="${COMMANDS[$i]}"
         command="${command//\[app-name\]/$APP_NAME}"
         command="${command//\[arguments\]/$ARGUMENTS}"
-        eval $command
+        # Attempt to run the command
+        if ! eval $command; then
+          # Extract the command name for error handling
+          cmd_name=$(echo "$command" | awk '{print $1}')
+          check_command "$cmd_name"  # Check if the command exists
+        fi
         exit 0
     fi
 done
